# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "ahci" "ohci_pci" "ehci_pci" "usb_storage" ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];
  boot.initrd.luks.devices = [ { device = "/dev/sda2"; name = "vault"; } ];

  fileSystems."/" =
    { device = "/dev/mapper/vault";
      fsType = "btrfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/e6d11e58-1489-4136-aeb4-71989b5cc516";
      fsType = "ext2";
    };

  swapDevices = [ ];

  nix.maxJobs = 2;
}
