# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "usb_storage" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];
  boot.initrd.luks.devices = [ { device = "/dev/disk/by-uuid/fe40ff72-4117-42fc-a71d-4c0274038310"; name = "vault"; } ];

  fileSystems."/" =
    { device = "/dev/ubuntu-vg/nixos";
      fsType = "btrfs";
    };

  fileSystems."/matlab" =
    { device = "/dev/ubuntu-vg/matlab";
      fsType = "ext4";
    };

  fileSystems."/steam" =
    { device = "/dev/ubuntu-vg/steam";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/F236-464E";
      fsType = "vfat";
    };

  swapDevices = [ ];

  nix.maxJobs = 8;
}
